spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path= /api/user/**
        - id: AUTH-SERVICE
          uri: lb://AUTH-SERVICE
          predicates:
            - Path= /api/authenticate/**
        - id: ACCOUNT-SERVICE
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path= /api/account/**
        - id: LOAN-SERVICE
          uri: lb://LOAN-SERVICE
          predicates:
            - Path= /api/loan/**

server:
  port: 9191
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 30
jwt:
  secret: mySecretKey
  expireMs: 1800000
  refrEshexpireMs: 1800000
